#! /bin/bash

if ! git diff-index --quiet HEAD
then
    echo "There are uncommitted changes, can't proceed."
    exit 1
fi

gitref=$(git rev-parse --short HEAD)
echo Proceed $gitref

docker build . -t cruz82/echoserver:$gitref -t cruz82/echoserver:latest

docker push cruz82/echoserver:$gitref -t cruz82/echoserver:latest
